export const SET_SELECTED_CONSOLES = "SET_SELECTED_CONSOLES";
export const SET_SELECTED_TYPES = "SET_SELECTED_TYPES";
export const SET_SELECTED_CONDITION = "SET_SELECTED_CONDITION";
export const SET_SELECTED_PRICE_RANGES = "SET_SELECTED_PRICE_RANGES";
export const SET_SELECTED_CONSOLES_BY_TYPE = "SET_SELECTED_CONSOLES_BY_TYPE";
export const SET_SELECTED_CONSOLES_BY_CONDITION =
  "SET_SELECTED_CONSOLES_BY_CONDITION";
export const SET_SELECTED_CONSOLES_BY_PRICE_RANGES =
  "SET_SELECTED_CONSOLES_BY_PRICE_RANGES";
