export const SET_SELECTED_GAMES = "SET_SELECTED_GAMES";
export const SET_SELECTED_PGRATINGS = "SET_SELECTED_PGRATINGS";
export const SET_SELECTED_GENRES = "SET_SELECTED_GENRES";
export const SET_SELECTED_GAMES_BY_PGRATING = "SET_SELECTED_GAMES_BY_PGRATING";
export const SET_SELECTED_GAMES_BY_GENRE = "SET_SELECTED_GAMES_BY_GENRE";
